[package]
name = "exeSystemProcessor"
version = "1.1.0"
authors = ["simon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psutil = { git = "https://github.com/borntyping/rust-psutil", tag = "v1.7.0" }
amqp = "*"
clap = "*"
simple_logger = "1.4.0"
log = "0.4"
serde = "*"
serde_json = "*"
serde_derive = "*"
cargo-tarpaulin = "0.10.2"
chrono = "0.4.10"

[dev-dependencies]
assert_cmd = "0.12.0"
predicates = "1.0.1"
glob = "0.3.0"
