name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
           rustc -V
           cargo -V
           cargo build --verbose
    - name: Run Audit
      run: |
           cargo install --force cargo-audit
           cargo generate-lockfile
           cargo audit
